name: Publish

on:
  push:
    branches: [master]
    paths: "**/Cargo.toml"

jobs:
  Publish:
    if: github.repository_owner == "BrainiumLLC"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1 # ensure crate order
      fail-fast: false
      matrix:
        crate:
          - { name: "rainbow-shared" }
          - { name: "rainbow-macros" }
          - { name: "rainbow" }
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.crate.target }}
          override: true
      - name: Publish ${{ matrix.crate.name }}
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: publish
          args: --manifest-path ${{ matrix.crate.name }}/Cargo.toml --token ${{ secrets.cratesio_token }}
